### ISSUE TITLE
api.spec

### ISSUE THREAD

**Issue by bsdlp** [ghickman/linode#6]
avoid maintenance of params.py and deviation from api spec by using the official api spec to generate api actions.

https://api.linode.com/?api_action=api.spec

**Comment by ghickman** [comment]
Started in `dynamic-params`.

@fly – happy to both work on this one together btw. Current work still needs to mock the new params to avoid hitting the API in the tests.

**Comment by bsdlp** [comment]
kk, looking now.

**Comment by bsdlp** [comment]
i made a couple minor edits here:

https://github.com/fly/linode/tree/dynamic-params

I'll continue to look at it when i get some time after work.

**Comment by ghickman** [comment]
I've pulled in those edits to the branch, thanks!

**Comment by ghickman** [comment]
@fly – Is there anything else you'd like me to pull into the `dynamic-params` branch? If not i'll merge and roll a release today.

**Comment by bsdlp** [comment]
wfm. i would like to add pep8 checks to the tests at some point. would you prefer if that was included in this release or next?

**Comment by ghickman** [comment]
I'll get this release out the door then we can add the pep8 bits in the next one. I'd like to add coverage to the tests too (should be easy with py.test now) so I'll probably make the next release a testing themed one.
